//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoTools.GeoServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoTools.GeoServer.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response with StatusCode {0}..
        /// </summary>
        internal static string Exception_GeoServerClientException {
            get {
                return ResourceManager.GetString("Exception_GeoServerClientException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization header value should consist of a schema with an optional parameter..
        /// </summary>
        internal static string Options_AuthorizationHeaderValueWrongFormat {
            get {
                return ResourceManager.GetString("Options_AuthorizationHeaderValueWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BaseAddress Uri can&apos;t point to a file..
        /// </summary>
        internal static string Options_BaseAddressFile {
            get {
                return ResourceManager.GetString("Options_BaseAddressFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BaseAddress Uri can&apos;t be null if ConfigureHttpClient isn&apos;t specified..
        /// </summary>
        internal static string Options_BaseAddressNull {
            get {
                return ResourceManager.GetString("Options_BaseAddressNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated options model is null..
        /// </summary>
        internal static string Options_Null {
            get {
                return ResourceManager.GetString("Options_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0} succeeded with response 200 OK..
        /// </summary>
        internal static string Request_200OK {
            get {
                return ResourceManager.GetString("Request_200OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0} succeeded with response 201 Created..
        /// </summary>
        internal static string Request_201Created {
            get {
                return ResourceManager.GetString("Request_201Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0} failed with response 401 Unauthorized..
        /// </summary>
        internal static string Request_401Unauthorized {
            get {
                return ResourceManager.GetString("Request_401Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0} failed with response 403 Forbidden..
        /// </summary>
        internal static string Request_403Forbidden {
            get {
                return ResourceManager.GetString("Request_403Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0} failed with response 404 Not Found..
        /// </summary>
        internal static string Request_404NotFound {
            get {
                return ResourceManager.GetString("Request_404NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0} failed with response 405 MethodNotAllowed..
        /// </summary>
        internal static string Request_405MethodNotAllowed {
            get {
                return ResourceManager.GetString("Request_405MethodNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0} failed with response 409 Conflict..
        /// </summary>
        internal static string Request_409Conflict {
            get {
                return ResourceManager.GetString("Request_409Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0} failed with response 500 InternalServerError..
        /// </summary>
        internal static string Request_500InternalServerError {
            get {
                return ResourceManager.GetString("Request_500InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} doesn&apos;t match the expected value {1}..
        /// </summary>
        internal static string Value_ComparisonMismatch {
            get {
                return ResourceManager.GetString("Value_ComparisonMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} is null..
        /// </summary>
        internal static string Value_Null {
            get {
                return ResourceManager.GetString("Value_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} is out of supported range {1}..
        /// </summary>
        internal static string Value_OutOfRange {
            get {
                return ResourceManager.GetString("Value_OutOfRange", resourceCulture);
            }
        }
    }
}
